### ISSUE TITLE
Neat architecture diagram you have! How did you do it? :) 

### ISSUE THREAD

**Issue by vedhas** [steadicat/pytorch-coreml-example#1]
Question related to the blog, and not the repo! How exactly did you draw the architecture image presented here? https://attardi.org/pytorch-and-coreml#architecture The diagram looks neat, and easy parameterise drawing tool is exactly something I am currently looking for! Kindly reply soon!

**Comment by steadicat** [comment]
The diagram was hand-drawn in Sketch. A tool to automate this would be neat!
